# Generated by Django 2.2.1 on 2019-05-28 22:26

from django.db import migrations, models
import tastypie.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('artnr', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=32)),
                ('created', models.DateTimeField(default=tastypie.utils.timezone.now)),
                ('updated', models.DateTimeField(default=tastypie.utils.timezone.now)),
            ],
        ),
    ]
