# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tastypie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiaccess',
            name='url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
